diff.astextplain.textconv=astextplain
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=main
user.name=Ashish Bahuguna
user.email=ashish_bahuguna@hotmail.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.editor=notepad++ -multiInst -nosession
credential.helper=wincred
gui.recentrepo=C:/Users/Ashish.Bahuguna/OneDrive - New Signature/Learnings/Terraform/hashicorp-certified
gui.recentrepo=C:/Users/Ashish.Bahuguna/OneDrive - New Signature/Learnings/Terraform/terraformonazure
safe.directory=C:/SourceControl/spicate-mct/caf-terraform-landingzones-accelerator
diff.tool=p4merge
difftool.p4merge.path=C:/Program Files/perforce/p4merge.exe
difftool.prompt=false
merge.tool=p4merge
mertgetool.p4merge.path=C:/Program Files/Perforce/p4merge.exe
mergetool.prompt=false
alias.hist=log --oneline --graph --decorate --all
push.default=simple
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/ashishbahuguna1975/my-website.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
